### ISSUE TITLE
I want to know something about Memory information

### ISSUE THREAD

**Issue by hisengberg** [marg-tools/CoMeT#10]
Dear Professors:
         I plan to write a custom Memory Bank DTM policy using CoMeT. While after looking at **_The CoMeT User Manaua_**, I have some questions about the Memory in 3D architecture in CoMeT. So, would you please help me solve these problems.
         1. In 3D architecture, whether the memory access time is uniform when a same core to access different memory bank?
         2. What is the default(no dram policy) mapping relationship between cores and memory banks?
         3. Is there an interface provided in CoMeT to specify the core to access some specific memory banks through algoritjms?
         4. I want to know what is the _**full_map**_ mean as well as **_limited_no_broadcast_** and _**limitless**_. as shown below.
![image](https://user-images.githubusercontent.com/118739669/203066182-1135ccd9-696d-43c8-8920-34db60d426d5.png)
         I would appreciate your help.
Yours sincerely,
Walter

**Comment by hisengberg** [comment]
BTW, the above problems are only for 3D-stacked configuration.

**Comment by anujpathania** [comment]
Hi Walter,

Here are some of the answers according to my understanding. 

1) Yes. I believe it is uniform. There is no modelling of a 3D-NoC yet that could result in non-uniform access time.

2) In default mapping, all cores can access all memory banks.

3) No. There is no such interface as of now. Building such an interface while mainlining memory consistency (and doesn't put simulations in a deadlock) would be non-trivial!

4)  This comes from Sniper originally. Look into Sniper forums if you can find something. Or write a mail to Sniper Dev.

**Comment by hisengberg** [comment]
i see, thank you for your help so much.
