### ISSUE TITLE
Error in Step 3.4 "Build verification test suite" 

### ISSUE THREAD

**Issue by SalmanAd01** [marg-tools/CoMeT#11]
![207262460-1f669dc4-8f8f-4b9c-8a59-f813c1035f81](https://user-images.githubusercontent.com/80933048/209506242-64947a29-03a8-4fee-aeca-e3bc8cb0911b.png)

**Comment by iTskAsra** [comment]
did you get this resolved?

**Comment by SalmanAd01** [comment]
> did you get this resolved?

Yep just delete everything and start from scratch

**Comment by Bao0319** [comment]
I also meet this error. change the option `scheduler/type=open` to `scheduler/type=pinned` in `config/base.cfg` might be able to solve the problem.

**Comment by shailjap29** [comment]
The error is not related to the verification test suite. Also, the **trace/benchmarks** parameter is needed only for the open scheduler in **common/scheduler/scheduler_open.cc** (scheduler/type=open in config/base.cfg). The open scheduler currently works only with the **--benchmarks** option of Sniper, used to run Parsec/Splash benchmark suite. Check Section 3.6 in README file. 

To execute an application binary /executable using **make run**, pls use pinned scheduler (scheduler/type=pinned in config/base.cfg).
