### ISSUE TITLE
Power-temperature mismatch during multi-core benchmarks when using subcore components

### ISSUE THREAD

**Issue by JorisoptenBerg** [marg-tools/CoMeT#13]
When subcore components are enabled per section 3.8 of the README, a mismatch between the power and temperature traces appears during benchmarks. 

For example, running parsec-blackscholes-simsmall-1 with configuration open+3.0GHz+constFreq gives a workload with one main and one worker core.
The components of core 0 increase in temperature when their power usage is high, as expected. The components of core 1 remain at a steady temperature for the duration of the benchmark, even as their power usage increases. Running the same benchmark without subcore components does give the expected results.

The relevant traces, `full_power_core.trace` and `full_temperature_core.trace`, along with simple visualisations of the relevant cores are atttached.

[full_power_core.trace.txt](https://github.com/marg-tools/CoMeT/files/11833239/full_power_core.trace.txt)
[full_power_core.trace.txt_C_0.pdf](https://github.com/marg-tools/CoMeT/files/11833240/full_power_core.trace.txt_C_0.pdf)
[full_power_core.trace.txt_C_1.pdf](https://github.com/marg-tools/CoMeT/files/11833241/full_power_core.trace.txt_C_1.pdf)
[full_temperature_core.trace.txt](https://github.com/marg-tools/CoMeT/files/11833242/full_temperature_core.trace.txt)
[full_temperature_core.trace.txt_C_0.pdf](https://github.com/marg-tools/CoMeT/files/11833243/full_temperature_core.trace.txt_C_0.pdf)
[full_temperature_core.trace.txt_C_1.pdf](https://github.com/marg-tools/CoMeT/files/11833244/full_temperature_core.trace.txt_C_1.pdf)

**Comment by kediarajesh** [comment]
Dear Joris,
Thanks for reporting this behavior. We identified a bug in the hotspot code, and am suggesting a temporary solution.
I am also including other contributors in this email.

The cause: Essentially, the leakage vector used to indicate if a memory channel or core is ON/OFF is of a limited length (16). In the sub-core mode, the number of units is large and all units beyond 16 units get the leakage vector value of 0 and hence are considered to be OFF. Thus, there is no power internally considered for the C_1 and hence the behavior that you saw.
Another problem is that the calc_core_leakage function is trained for a particular area of core and hence the leakage power is very high for some small units, making their temperature shoot up. As a temporary hack, we disable consideration of leakage vector or leakage function for the sub-core components.

Can you please try the following change for the sub-core and re-run your experiments?

In hotspot_tool/temperature.c, search for "//for Core" or "Core" (there are two such occurrences). Below both of these, please modify the code as follows (and do a make in the hotspot_tool folder):
original:
if (leakage[j] == 0)
power_new[base+j] = 0;
else
power_new[base+j] = power[base+j] + ((float) volt[j]/10) * calc_core_leakage(model->config->leakage_mode,blk_height,blk_width,temp[base+j]);

Modified:
power_new[base+j] = power[base+j];

Regarding a long-term fix, we will need to relook into some details and would then get back.

Regards,
Rajesh

**Comment by siddhulokesh** [comment]
For now, the suggested solution is checked-in so that the mismatch does not occur.
