### ISSUE TITLE
Is there a limit on the number of cores when creating Floorplans ,or I just miss something 

### ISSUE THREAD

**Issue by xlxwzybds** [marg-tools/CoMeT#23]
Dear Sir/Madam ,

I had some problems when I wanted to create floorplans called `DDR_64_cores`. The command.txt is 
```shell
python3 floorplanlib/create.py --mode DDR --cores 8x8 --corex 1.0mm --corey 1.0mm --banks 4x4 --bankx 1.0mm --banky 1.0mm --out config/hotspot/DDR_64core/
```

The problem shows that when the Core number of the index is `> 15`, the reading temperature is the default temperature (for example, Core 16). Specific performance is as follows
```shell
[Scheduler]: DVFS Control Loop invoked at 19.000.000 ns
[Scheduler][DVFS_MAX_FREQ]: Core 9: P= 0.821W f=4000 MHz T= 59.4C utilization=0.000
[Scheduler][DVFS_MAX_FREQ]: Core 10: P= 8.087W f=4000 MHz T= 106.2C utilization=0.894
[Scheduler][DVFS_MAX_FREQ]: Core 11: P=8.648 W f=4000 MHz T=112.9 C utilization=0.892
[Scheduler][DVFS_MAX_FREQ]: Core 12: P=8.374 W f=4000 MHz T=110.4 C utilization=0.895
[Scheduler][DVFS_MAX_FREQ]: Core 13: P=8.352 W f=4000 MHz T= 109.9C utilization=0.892
[Scheduler][DVFS_MAX_FREQ]: Core 14: P=8.607 W f=4000 MHz T= 111.8C utilization=0.891
[Scheduler][DVFS_MAX_FREQ]: Core 15: P= 7.804W f=4000 MHz T= 104.2C utilization=0.892
[Scheduler][DVFS_MAX_FREQ]: Core 16: P= 8.728W f=4000 MHz T= 46.6C utilization=0.891
```

When I use CoMeT's default DDR_16core floorplan to run runlib.get_instance `('parsec-blackscholes', parallelism=8, input_set='small')` benchmark, no problem. I then created a floorplan with `DDR_64cores`. 
I changed the `mapFirstUnused.cc` code to specify running the `0-1-2-3-4-5-6-7` cores to run the task without any problems. I also specified the cores `8-9-10-11-12-13-14-15` to run the task without any problems.

The problem arises when I use the cores `0-1-2-3-4-5-6-16`. Even though the `Core-16` operates at around `8W`, the temperature invoked with *performance is maintained at the initial temperature (`45C`).
My creation process includes:
1. Use CoMeT floorplan python code to create `DDR_64core`.
2. Add the config file named `gainestown_DDR_64core.cfg` and change the number of cores.
3. Change the number of cores in based config file `base.cfg` .
4. Modify the `simulationcontrol/config.py` of indexes;
5. Modify `mapFirstUnused.cc` to force `Core-16` to be used.

After many attempts, I still haven't found an effective way to solve this problem. I think there may have been some problems with my creation process that I overlooked.

Yours sincerely,
Jiayan

**Comment by janjanjan20** [comment]
Hi Jiayan,

what variables have you changed in the new config file? I think the following variables need to be adjusted  based on your new floorplan:
[general]
total_cores = 16

[memory]
cores_in_x = 4                      # total cores in x-dimension
cores_in_y = 4                      # total cores in y-dimension

[hotspot]
floorplan_folder  = config/hotspot/DDR_16core   

init_file_external_mem = config/hotspot/DDR_16core/mem.init
hotspot_config_file_mem  =  config/hotspot/DDR_16core/mem_hotspot.config 
layer_file_mem  =   config/hotspot/DDR_16core/mem.lcf   


init_file_external_core = config/hotspot/DDR_16core/cores.init
hotspot_config_file_core  =  config/hotspot/DDR_16core/cores_hotspot.config 
layer_file_core  =   config/hotspot/DDR_16core/cores.lcf 


Also, any setting in gainestown_DDR_64core.cfg will overwrite the settings of the base.cfg. Setting the number of cores in gainestown_DDR_64core.cfg to 64 is thus enough, there is no need to also change the number of cores in base.cfg. 

I assume you also changed the SNIPER_CONFIG in simulationcontrol/config.py to your new configuration file? I hope any of my suggestion will be helpful!

Kind regards,
Jan

**Comment by xlxwzybds** [comment]
> Hi Jiayan,
> 
> what variables have you changed in the new config file? I think the following variables need to be adjusted based on your new floorplan: [general] total_cores = 16
> 
> [memory] cores_in_x = 4 # total cores in x-dimension cores_in_y = 4 # total cores in y-dimension
> 
> [hotspot] floorplan_folder = config/hotspot/DDR_16core
> 
> init_file_external_mem = config/hotspot/DDR_16core/mem.init hotspot_config_file_mem = config/hotspot/DDR_16core/mem_hotspot.config layer_file_mem = config/hotspot/DDR_16core/mem.lcf
> 
> init_file_external_core = config/hotspot/DDR_16core/cores.init hotspot_config_file_core = config/hotspot/DDR_16core/cores_hotspot.config layer_file_core = config/hotspot/DDR_16core/cores.lcf
> 
> Also, any setting in gainestown_DDR_64core.cfg will overwrite the settings of the base.cfg. Setting the number of cores in gainestown_DDR_64core.cfg to 64 is thus enough, there is no need to also change the number of cores in base.cfg.
> 
> I assume you also changed the SNIPER_CONFIG in simulationcontrol/config.py to your new configuration file? I hope any of my suggestion will be helpful!
> 
> Kind regards, Jan




Hi , Jan 
Thank you for your quick and detailed recovery.

According to your information, I have repeatedly confirmed whether the parameters I modified are correct or missing. After checking, I made sure that my config changes were modified exactly as you replied. Unfortunately, there is still a problem with hotspot calculating the core temperature incorrectly.

I think this problem may be a segment fault and only have something to do with my PC.

I decide to keep this issue open for a week and then close it. During this period, if I solve my personal problem, I will share how to solve it after the issue.

Thank you again for your detailed help.

Yours sincerely,
Jiayan

**Comment by kediarajesh** [comment]
This is an interesting observation. Thanks.
I believe this behavior might come due to the use of the following code in temperature.c (when calculating core temperature):
							
							if (leakage[j] == 0)
								power_new[base+j] = 0;
							else	
								power_new[base+j] = power[base+j] + ((float) volt[j]/10) * calc_core_leakage(model->config->leakage_mode,blk_height,blk_width,temp[base+j]);
		 					// printf("YES");
							
The default setup has ' -l 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1, ' being used where we specify leakage[] as 1 for only 16 values. So, the other values of leakage[] array gets initialized to 0 and hence it ignores the power for cores beyond 16.

To confirm that this is the cause, please bypass the if (leakage[j] == 0) check and see if matches the expectations. If it does, we can discuss the potential fix.

**Comment by xlxwzybds** [comment]
> This is an interesting observation. Thanks. I believe this behavior might come due to the use of the following code in temperature.c (when calculating core temperature):
> 
> ```
> 						if (leakage[j] == 0)
> 							power_new[base+j] = 0;
> 						else	
> 							power_new[base+j] = power[base+j] + ((float) volt[j]/10) * calc_core_leakage(model->config->leakage_mode,blk_height,blk_width,temp[base+j]);
> 	 					// printf("YES");
> ```
> 
> The default setup has ' -l 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1, ' being used where we specify leakage[] as 1 for only 16 values. So, the other values of leakage[] array gets initialized to 0 and hence it ignores the power for cores beyond 16.
> 
> To confirm that this is the cause, please bypass the if (leakage[j] == 0) check and see if matches the expectations. If it does, we can discuss the potential fix.

Hi ,kediarajesh
    Thank you for your help. Your advice is very effective.
    Based on your suggestions, I rebuilt a `DDR_25` floorplan and modified the hotspot call script `memTherm_core.py` while running.
     I also tried to modify the command `'-l 1,1,1,1,1'` before, but I added a `'1'` after `'-l '` in order to call the core `0-1-2-3-4-5-6-16`, but it didn't work.
Based on my attempts, it seems that the `'-l'` must have as many `'1, '` as the number of cores in `DDR_25core` floorplan.

Yours sincerely,
Jiayan
