### ISSUE TITLE
can't build docker image

### ISSUE THREAD

**Issue by Casparyyds** [marg-tools/CoMeT#6]
Dear ir or madam:
My ubuntu's version is 18.04 and after I installed Docker, I couldn’t use “make” to build the Docker image, and it prompted a version problem of gcc++. Another problem that made me wonder is that there is already version 3.7 pin_kit in the CoMeT folder, why should I download the 3.2 version of pin_kit to replace it.again? And there is a pin3.15 compressed package in the CoMeT root folder.
Looking forward to get your reply soon！Thank you.

**Comment by shailjap29** [comment]
Could you share the screenshot after you run make inside the docker folder?

**Comment by shailjap29** [comment]
You need not download pin_kit 3.2 version. It will be auto-downloaded. pin_kit 3.7 is specifically used to support running SPEC pinballs in CoMeT.

**Comment by Casparyyds** [comment]
thank you. i already downloaded it successfully.
