### ISSUE TITLE
malloc():corrupted top size

### ISSUE THREAD

**Issue by Casparyyds** [marg-tools/CoMeT#7]
Hi!
I followed the Readme tutorial to the last step, "Running an Application", but when I use `make run | tee logfile`, the expected result does not appear, but `malloc():corrupted top size` appears, what is the reason for this?
Hope to get your reply soon, thanks!

**Comment by shailjap29** [comment]
Hi, 
Is the sim.out file non-empty? Looks like the simulation failed for some reason. Could you share the screenshot of the content of the logfile towards the end?

**Comment by Casparyyds** [comment]
Thank you very much for your reply, I will add some details of my operating environment: the system version is: 20.04, and the ubuntu_version in the Makefile in the docker folder is also 20.04.
The sim.out file is non-empty, please see the figure below for details; and the screenshot of the content of the logfile towards the end is here.
![malloc](https://user-images.githubusercontent.com/97741146/190896260-ff1b27cd-3568-4c1a-ab32-3b641fc01ed7.png)
![sim out](https://user-images.githubusercontent.com/97741146/190896263-8d631f9a-553c-408e-8a27-7d7dad8b470b.png)

Hope to get your reply soon, thanks!

**Comment by shailjap29** [comment]
Your simulation went fine, and the sim.out file is valid. Could you try  "make clean" and "make" in the CoMeT folder. And then run thermal example (also, do a make clean here as well).

**Comment by Casparyyds** [comment]
thank you. i already downloaded it successfully.
