### ISSUE TITLE
Thermal model of Core-3D NUCA System

### ISSUE THREAD

**Issue by Casparyyds** [marg-tools/CoMeT#8]
Dear Sir,
I have been using your EDA tool for a while, I would like to ask if CoMeT supports the thermal models of Core-3d S-NUCA Systems in addition to supporting 3D Processor-Memory Systems？
Hope to get your reply soon, thanks!
Yours sincerely,
Caspar

**Comment by anujpathania** [comment]
Hi Caspar,

Is Core-3D S-NUCA different from S-NUCA in 2D processors?

We have not used S-NUCA per say in CoMeT, but I guess it should work out-of-the-box. The support for S-NUCA comes from original Sniper. 

Nevertheless, we have used (and published) using S-NUCA extensively for 2D processors  with HotSniper (https://github.com/anujpathania/HotSniper), which was predecessor of CoMeT in spirit.

**Comment by anujpathania** [comment]
Hi Caspar,

The stacking in CoMeT, by default, is for DRAM main memory banks not Cache banks.Caches are still within the same layer as processors in CoMeT.

If you want caches (L2 I assume) in a seperate layer, I am afraid you will have to implement that feature yourself. Same goes for Cache bank zones.

-- Anuj

**Comment by Casparyyds** [comment]
i see, thank you for your reply, maybe i can try to use CoMeT to research related NUMA architecture.
